# Stage 1: Train Encoder/Decoder (Freeze Transformer)
# Goal: Learn good PDE feature representations

stage: 1
model_name: "pde_stage1"

# Dataset
dataset:
  path: "/home/msai/song0304/code/PDE/data"
  temporal_length: 16
  train_ratio: 0.9
  seed: 42

# DataLoader
dataloader:
  batch_size: 2
  num_workers: 4
  pin_memory: true
  same_sample_per_batch: true

# Model (same as llama_1b)
model:
  in_channels: 6
  noise_level: 0
  use_flash_attention: false
  gradient_checkpointing: true

  transformer:
    hidden_size: 2048
    num_hidden_layers: 16
    num_attention_heads: 32
    num_key_value_heads: 8
    intermediate_size: 8192
    hidden_act: "silu"
    max_position_embeddings: 4096
    rms_norm_eps: 1.0e-5
    rope_theta: 500000.0
    attention_dropout: 0.0

# Freeze config
freeze:
  transformer: true   # FROZEN
  encoder: false      # TRAINABLE
  decoder: false      # TRAINABLE

# Training
training:
  max_steps: 2000
  pretrain_from: null
  learning_rate: 1.0e-4
  weight_decay: 1.0e-4
  betas: [0.9, 0.999]
  grad_clip: 1.0
  min_lr: 1.0e-6
  warmup_steps: 20

  loss_alpha: 0.0      # Pure MSE (fast convergence for large errors)
  nrmse_sigma: null

  mixed_precision: "bf16"
  gradient_accumulation_steps: 1

  # save_every_steps: 500  # Disabled for staged training
  eval_every_steps: 50
  early_stopping_patience: 10

# Logging
logging:
  project: "pde-staged"
  entity: "reca1c1trant-ntu"
  save_dir: "./checkpoints_stage1"
  log_interval: 10
