# Stage 3: End-to-End Fine-tuning (All Trainable)
# 新架构: 768 hidden_size + V2 Encoder (ResBlock)

stage: 3
model_name: "pde_v2_stage3"

# Dataset
dataset:
  path: "/home/msai/song0304/code/PDE/data"
  temporal_length: 16
  train_ratio: 0.9
  seed: 42

# DataLoader
dataloader:
  batch_size: 4
  num_workers: 4
  pin_memory: true
  same_sample_per_batch: false

# Model - 新配置 (~125M 参数)
model:
  in_channels: 6
  noise_level: 0.0     # 关闭噪声用于 fine-tuning
  use_flash_attention: false
  gradient_checkpointing: true

  # V2 Encoder 配置 (方案 A+B)
  encoder:
    version: "v2"
    mid_channels: 512
    use_resblock: true

  # Transformer - 缩小版 (~125M)
  transformer:
    hidden_size: 768
    num_hidden_layers: 12
    num_attention_heads: 12
    num_key_value_heads: 4
    intermediate_size: 3072
    hidden_act: "silu"
    max_position_embeddings: 4096
    rms_norm_eps: 1.0e-5
    rope_theta: 500000.0
    attention_dropout: 0.0

# Freeze config
freeze:
  transformer: false  # TRAINABLE
  encoder: false      # TRAINABLE
  decoder: false      # TRAINABLE

# Training
training:
  max_steps: 4000
  pretrain_from: "./checkpoints_v2_stage2/best.pt"
  learning_rate: 1.0e-5   # 较小的 LR 用于 fine-tuning
  weight_decay: 1.0e-4
  betas: [0.9, 0.999]
  grad_clip: 1.0
  min_lr: 1.0e-7
  warmup_steps: 200

  loss_alpha: 0.5         # MSE + RMSE 混合
  nrmse_sigma: [0.143810, 0.111739, 0.0, 0.0, 0.0, 0.0]

  mixed_precision: "bf16"
  gradient_accumulation_steps: 1

  save_every_steps: 500
  eval_every_steps: 50
  early_stopping_patience: 15

# Logging
logging:
  project: "pde-v2"
  entity: "reca1c1trant-ntu"
  save_dir: "./checkpoints_v2_stage3"
  log_interval: 10
