# Stage 2: Train Transformer (Encoder/Decoder Frozen)
# 新架构: 768 hidden_size + V2 Encoder (ResBlock)

stage: 2
model_name: "pde_v2_stage2"

# Dataset
dataset:
  path: "/home/msai/song0304/code/PDE/data"
  temporal_length: 16
  train_ratio: 0.9
  seed: 42

# DataLoader
dataloader:
  batch_size: 8
  num_workers: 4
  pin_memory: true
  same_sample_per_batch: true

# Model - 新配置 (~125M 参数)
model:
  in_channels: 6
  noise_level: 0
  use_flash_attention: false
  gradient_checkpointing: true

  # V2 Encoder 配置 (方案 A+B)
  encoder:
    version: "v2"
    mid_channels: 512
    use_resblock: true

  # Transformer - 缩小版 (~125M)
  transformer:
    hidden_size: 768
    num_hidden_layers: 16
    num_attention_heads: 12
    num_key_value_heads: 4
    intermediate_size: 3072
    hidden_act: "silu"
    max_position_embeddings: 4096
    rms_norm_eps: 1.0e-5
    rope_theta: 500000.0
    attention_dropout: 0.0

# Freeze config
freeze:
  transformer: false  # TRAINABLE
  encoder: true     
  decoder: true    

# Training
training:
  max_steps: 2000
  pretrain_from: "./checkpoints_v2_stage1/best.pt"
  learning_rate: 1.0e-5
  weight_decay: 1.0e-5
  betas: [0.9, 0.999]
  grad_clip: 5.0
  min_lr: 1.0e-6
  warmup_steps: 100

  loss_alpha: 1     # Pure nRMSE
  nrmse_sigma: [0.143810, 0.111739, 0.0, 0.0, 0.0, 0.0]

  mixed_precision: "bf16"
  gradient_accumulation_steps: 1

  eval_every_steps: 20
  early_stopping_patience: 10

# Logging
logging:
  project: "pde-v2"
  entity: "reca1c1trant-ntu"
  save_dir: "./checkpoints_v2_stage2"
  log_interval: 10
